//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionSite.Localize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuctionSite.Localize.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are a lot of interesting rules..... bla bla bla.....
        /// </summary>
        public static string Action_rules {
            get {
                return ResourceManager.GetString("Action_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification passed.
        /// </summary>
        public static string Admin_page_verification_passed {
            get {
                return ResourceManager.GetString("Admin_page_verification_passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Common_Create {
            get {
                return ResourceManager.GetString("Common_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency selection.
        /// </summary>
        public static string Currency_selection {
            get {
                return ResourceManager.GetString("Currency_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownLoad.
        /// </summary>
        public static string DownLoad {
            get {
                return ResourceManager.GetString("DownLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Login or Password.
        /// </summary>
        public static string Error_Login_Wrong_Login_or_Password {
            get {
                return ResourceManager.GetString("Error_Login_Wrong_Login_or_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Login please..
        /// </summary>
        public static string Input_Login_please {
            get {
                return ResourceManager.GetString("Input_Login_please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input password please.
        /// </summary>
        public static string Input_password_please {
            get {
                return ResourceManager.GetString("Input_password_please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscribe.
        /// </summary>
        public static string Item_subscribe {
            get {
                return ResourceManager.GetString("Item_subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LayOut_Auth_Login {
            get {
                return ResourceManager.GetString("LayOut_Auth_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LayOut_Auth_Logout {
            get {
                return ResourceManager.GetString("LayOut_Auth_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string LayOut_Auth_Registration {
            get {
                return ResourceManager.GetString("LayOut_Auth_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Page.
        /// </summary>
        public static string LayOut_menu_Admin_page {
            get {
                return ResourceManager.GetString("LayOut_menu_Admin_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction rules.
        /// </summary>
        public static string LayOut_menu_Auction_rules {
            get {
                return ResourceManager.GetString("LayOut_menu_Auction_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        public static string LayOut_menu_Forum {
            get {
                return ResourceManager.GetString("LayOut_menu_Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string LayOut_menu_Main {
            get {
                return ResourceManager.GetString("LayOut_menu_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal account.
        /// </summary>
        public static string LayOut_menu_Personal_account {
            get {
                return ResourceManager.GetString("LayOut_menu_Personal_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a lot.
        /// </summary>
        public static string LayOut_menu_Set_a_lot {
            get {
                return ResourceManager.GetString("LayOut_menu_Set_a_lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antiques.
        /// </summary>
        public static string LayOut_Types_Antiques {
            get {
                return ResourceManager.GetString("LayOut_Types_Antiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string LayOut_Types_Books {
            get {
                return ResourceManager.GetString("LayOut_Types_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string LayOut_Types_Equipment {
            get {
                return ResourceManager.GetString("LayOut_Types_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string LayOut_Types_Others {
            get {
                return ResourceManager.GetString("LayOut_Types_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        public static string LayOut_Types_Vehicles {
            get {
                return ResourceManager.GetString("LayOut_Types_Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Login_Registration {
            get {
                return ResourceManager.GetString("Login_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a new lot.
        /// </summary>
        public static string Lot_SetLot_Creating__a_new_lot {
            get {
                return ResourceManager.GetString("Lot_SetLot_Creating _a_new_lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place a bet.
        /// </summary>
        public static string Lot_Show_Place_a_bet {
            get {
                return ResourceManager.GetString("Lot_Show_Place_a_bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no lots more. Thank you))..
        /// </summary>
        public static string Message_end_admin_check {
            get {
                return ResourceManager.GetString("Message_end_admin_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks. Your lot has been sent for moderation..
        /// </summary>
        public static string Message_end_set_Lot {
            get {
                return ResourceManager.GetString("Message_end_set_Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You raised the price on the lot.
        /// </summary>
        public static string Place_bet_finish_phrase {
            get {
                return ResourceManager.GetString("Place_bet_finish_phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your favorite types of lot.
        /// </summary>
        public static string Profile_input_FavotiteTypeOfLot {
            get {
                return ResourceManager.GetString("Profile_input_FavotiteTypeOfLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input  your name.
        /// </summary>
        public static string Profile_input_Name {
            get {
                return ResourceManager.GetString("Profile_input_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input  your phone number.
        /// </summary>
        public static string Profile_input_PhoneNumber {
            get {
                return ResourceManager.GetString("Profile_input_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input  your surname.
        /// </summary>
        public static string Profile_input_Surname {
            get {
                return ResourceManager.GetString("Profile_input_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password .
        /// </summary>
        public static string Registration_Confirm_password {
            get {
                return ResourceManager.GetString("Registration_Confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input email.
        /// </summary>
        public static string Registration_Input_email {
            get {
                return ResourceManager.GetString("Registration_Input_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Login.
        /// </summary>
        public static string Registration_Input_Login {
            get {
                return ResourceManager.GetString("Registration_Input_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input password.
        /// </summary>
        public static string Registration_Input_password {
            get {
                return ResourceManager.GetString("Registration_Input_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose type of lot.
        /// </summary>
        public static string Set_lot_Choose_type_of_lot {
            get {
                return ResourceManager.GetString("Set_lot_Choose_type_of_lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input lot discription.
        /// </summary>
        public static string Set_lot_Input_lot_discription {
            get {
                return ResourceManager.GetString("Set_lot_Input_lot_discription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input lot name.
        /// </summary>
        public static string Set_lot_Input_lot_name {
            get {
                return ResourceManager.GetString("Set_lot_Input_lot_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input start price.
        /// </summary>
        public static string Set_lot_Input_start_price {
            get {
                return ResourceManager.GetString("Set_lot_Input_start_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Name of lot please..
        /// </summary>
        public static string Set_lot_Mistake_Input_Name {
            get {
                return ResourceManager.GetString("Set_lot_Mistake_Input_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks. You subscribed on lot .
        /// </summary>
        public static string Subscribe_finish {
            get {
                return ResourceManager.GetString("Subscribe_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Lots.
        /// </summary>
        public static string User_Page_Active_lots {
            get {
                return ResourceManager.GetString("User_Page_Active_lots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change profile.
        /// </summary>
        public static string User_Page_Change_Profile {
            get {
                return ResourceManager.GetString("User_Page_Change_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string User_Page_History {
            get {
                return ResourceManager.GetString("User_Page_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Lots.
        /// </summary>
        public static string User_Page_Rejected_Lots {
            get {
                return ResourceManager.GetString("User_Page_Rejected_Lots", resourceCulture);
            }
        }
    }
}
